# Generated by Django 4.2.2 on 2023-06-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='benefit',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='recommended_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='required_gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not important')], default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='required_graduation',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'primary'), (2, 'secondary'), (3, 'high school'), (4, 'bachelor'), (5, 'master'), (6, 'doctor'), (7, 'professor')], default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='required_level',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Junior'), (3, 'Senior'), (4, 'Expert'), (5, 'Master'), (6, 'Grand Master'), (7, 'Legendary'), (8, 'None')], default=8),
        ),
    ]
