# Generated by Django 4.2.2 on 2023-07-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_skill_options_score_joboffer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='jobs.skill'),
        ),
    ]
